### ISSUE TITLE
Move visible drop to other workspace

### ISSUE THREAD

**Issue by quite** [noctuid/tdrop#21]
I'm on mate/marco. When a tdrop:ed window is mapped on another workspace and I call tdrop while on another workspace, I would ideally have the window remapped to this current workspace. This does not happen. Neither does calling tdrop two times achieve this behaviour. Is this intended? The comment in the readme regarding awesome wm makes me think that this functionality should perhaps already be present...

**Comment by noctuid** [comment]
This isn't necessarily intentional. The reason that tdrop behaves differently for awesome is that most other WMs (every other one I've tried it with) report windows on other desktops/workspaces as unmapped. Furthermore, you can't unmap a window that is open on another desktop with xdotool.

I agree that the behavior you describe would be nicer, but I'm not sure the best way of achieving it. #18 could make this unecessary. Alternatively, xdotool has a command that allows moving a window to another desktop. I've implemented it this way, but there are a couple potential problems. I'm not sure if the command works consistently across WMs (but I think that it does), so please test it, and I'll try it on some other WMs when I get a chance.

**Comment by PwnArt1st** [comment]
+1

**Comment by quite** [comment]
Your addition worked fine here on mate/marco. Thanks a bunch, this is really great for the workflow.
