### ISSUE TITLE
Feature request: Hide dropdown window on first startup

### ISSUE THREAD

**Issue by alekcacko** [noctuid/tdrop#34]
Is it easy to implement a feature that will start dropdown window in background so we can add it to autostart with some window manager?

For example: 
In ~/.config/openbox/autostart

tdrop -ma -w -4 -y "$PANEL_HEIGHT" **-hide** termite

Or in i3 config file:

exec --no-startup-id tdrop -ma -w -4 -y "$PANEL_HEIGHT" **-hide** termite

**Comment by noctuid** [comment]
I'm not sure. The startup time of termite and most terminals is pretty negligible, so I'm not sure I see the advantage of this. You can try using `--post-create-hook`/`-C`: `tdrop -ma -w -4 -y "$PANEL_HEIGHT" -C 'xdotool windowunmap $wid'

**Comment by alekcacko** [comment]
I see. The issue can be closed.

**Comment by noctuid** [comment]
For information about improving flicker in general, see [here](https://github.com/noctuid/tdrop#flicker). As for flicker caused by immediately unmapping the window after first running the program, this may not help, and I don't know of any way to prevent this. The program would need to be run without allowing any windows to be mapped, or any created windows would need to be unmapped before they were drawn, and I have no idea whether that is possible. I don't see the use case for immediately hiding though.

**Comment by alexozer** [comment]
Ah I see how it might be non-straightforward to implement then. Use cases might include backgrounding programs like Spotify when logging in, ready to toggle when I want.

**Comment by noctuid** [comment]
I'd say this is out of the scope of tdrop and would better be handled by the window manager (e.g. by spawning the window on a background desktop/workspace) or another wrapper dedicated to keeping windows spawned by a program in the background. If there was such a program, I wouldn't be opposed to using it to add a `--hide` flag to prevent flickering.
