### ISSUE TITLE
[Openbox] Can't summon tdrop again after calling and dissmising it once in a blank screen.

### ISSUE THREAD

**Issue by agoodfellow123** [noctuid/tdrop#349]
This is an odd one so I'll explain how you can replicate it:

1. Run openbox.
2. Do not run anything else, the active screen must be empty.
3. Call tdrop, the terminal will appear.
4. Dismiss it in the same way you call it.
5. You no longer can call it with the same combination.

Note that it works perfectly fine when there is another application running on the active screen. Only when there is nothing this bug will occur. In case you can not replicate it here is how it call it: `tdrop -m -a -w 70% -h 70% -x 15% -y 15% -n sPPulseMixer alacritty -e pulsemixer`

**Comment by noctuid** [comment]
Can you try with the latest tdrop and see if you still have the issue?

**Comment by agoodfellow123** [comment]
Manjaro has the version 0.4.0-2 which has the problem, I will try with the latest version as soon as it's updated on manjaro repos.

**Comment by noctuid** [comment]
I think it will still be broken. I am having trouble setting openbox to debug this. If you have a chance, can you follow these steps and give me the output?

1. Run this in bash (e.g. if you use zsh or another shell, run `bash` first)
```
test_fn() {
	wid=999
	if [[ $(xdotool getactivewindow) != "$wid" ]]; then
		echo "not the same"
	else
		echo "the same"
	fi
	echo "$(xdotool getactivewindow)"
}
```
2. Run `sleep 4 && test_fn`, switching to an empty desktop during the sleep time so that test_fn runs on an empty desktop
3. Copy an output including errors and comment it here

> Manjaro has the version 0.4.0-2

Is tdrop in the official manjaro repos? If you are using the tdrop package from the aur, I recommend using tdrop-git instead. The tdrop aur package is not mine.

**Comment by agoodfellow123** [comment]
I did what you instructed, it did the bug again and returned:

`not the same`
`50331652`

> Is tdrop in the official manjaro repos?

My mistake, it's not on manjaro repos, I had it in aur. Let me switch to tdrop-git and try again.

**Comment by agoodfellow123** [comment]
With the git version it also did the bug and returned:

`not the same`
`102760452`

Not only that but git version introduced a new bug. I call tdrop with the command `exec tdrop -m -a --wm bspwm -w 70% -h 70% -x 15% -y 15% -n sPPulseMixer alacritty -e pulsemixer` and with the non git aur version that works perfectly fine both on bspwm and openbox, it basically shows my terminal in the middle of the screen. But after installing the git version it didn't show up in the middle of the screen when there is other things on the desktop, instead picked a random corner for each desktop and appeared there, not only that but also completely ignored the size requirements too. It did show in the right place and right size when there was nothing on the desktop though.

**Comment by noctuid** [comment]
> 50331652

`xdotool getactivewindow` returned a window id on an empty desktop? That's bizarre but could explain the bug. What window id is this? Is that the last focused windowid or something completely different? After running `test_fn`, check the window id of the terminal with `xdotool getactivewindow` and see if they match.

Could you also test what happens if you replace `xdotool getactivewindow` with `xdotool getwindowfocus` in test_fn and follow the same steps?

> But after installing the git version it didn't show up in the middle of the screen

On bspwm, openbox, or both? That command definitely will not work for openbox because of `--wm bspwm`. You also don't need to specify `--wm` on bspwm.

**Comment by agoodfellow123** [comment]
Ok, so I realized i made a mistake, after `test_fn` I had to switch to an empty desktop and do nothing correct? Well instead of that i switched to it and then launch tdrop. Sorry about that, I just now realized what you meant. Here is the correct output:

```
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
not the same
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
```

> On bspwm, openbox, or both? That command definitely will not work for openbox because of --wm bspwm.

Just tried on openbox. Funny thing is the command did worked on openbox despite the --wm bspwm argument.

> You also don't need to specify --wm on bspwm.

It didn't work correctly on bspwm when i tried without the --wm argument.

**Comment by noctuid** [comment]
> Funny thing is the command did worked on openbox despite the --wm bspwm argumen

Are you using multiple monitors? If you specify `--wm bspwm` it will not be able to correctly detect the current monitor.

> It didn't work correctly on bspwm when i tried without the --wm argument.

What version of bspwm are you on?

**Comment by noctuid** [comment]
Your command works as expected for me on bspwm 0.9.10 without `--wm bspwm` or the issue you describe, regardless of how many windows are open.

**Comment by agoodfellow123** [comment]
No, I'm on single monitor.
Bspwm 0.9.10-1

**Comment by noctuid** [comment]
I can't replicate. How are you binding the key? can you post the sxhkdrc lines if you're using sxhkd?

**Comment by agoodfellow123** [comment]
I run the tdrop script with right-clicking the voice icon on my polybar like this:

```
[module/pulseaudio]
type = internal/pulseaudio

.
.
.

click-right = exec tdrop -m -a --wm bspwm -w 70% -h 70% -x 15% -y 15% -n sPPulseMixer alacritty -e pulsemixer
```

**Comment by noctuid** [comment]
Please try on the latest tdrop. Also try with `-A` (even though you don't use it) to confirm the issue no longer exists.

> I run the tdrop script with right-clicking the voice icon on my polybar like this:

Your script works fine for me on the same version of bspwm, and I do not need to use `--wm`. Please open a new issue if you still have this problem. Do you have any bspwm rules that could be affecting things? Do you have xrandr installed?

**Comment by agoodfellow123** [comment]
So I have the aur git version and I tried to run on bspwm without --wm. Sadly the results are the same, tdrop window does not float it tiles when I don't have --wm flag.

**Comment by noctuid** [comment]
This is probably a configuration issue. Do you have something like `wmname LG3D` in your xinitrc or bspwmrc? If so, that would explain it.

Are you still having the other issue?

**Comment by noctuid** [comment]
> I do have wmname LG3D they recommend that you keep that there.

This is potentially useful for some java applications. It broke way too many things for me, and I almost never use java applications (and `export _JAVA_AWT_WM_NONREPARENTING=1` was enough to get them working), so I removed it from my config.

> But last I checked with --wm it still had the problem.

1. Make sure you are on the latest commit (update tdrop-git if you didn't already today)
2. Make sure you have xrandr installed
3. Try again
4. Since you are on a single monitor, you can also try without `-m`

**Comment by agoodfellow123** [comment]
Ok, I did what you suggested. Tdrop works perfectly fine on both window managers now. I don't have a java program to test so I guess the issue can be closed. Thank you for everything.
