### ISSUE TITLE
add option to execute hook inside the window

### ISSUE THREAD

**Issue by chris-aeviator** [noctuid/tdrop#423]
### Motivation

Sometimes it would be benefitial if a hook could be executed inside the window that I'm opening/ re opening. One of this examples is mapping a tdrop for administrative tasks and wanting to 
``
clear 
``
the terminal and buffer 
``
clear clear
``
or 
`
tput reset
`

All of these will have no effect on the opened tdrop currently.

`
tdrop -am --post-map-hook="tput reset"  alacritty
` 
### Current
![grafik](https://github.com/noctuid/tdrop/assets/11522213/7f88d69b-b60c-48d9-98a0-832718d0baa0)

upon re open

(same)

### Desired

![grafik](https://github.com/noctuid/tdrop/assets/11522213/87459e71-bdae-4656-a754-e849909d6d0c)

upon re open
![grafik](https://github.com/noctuid/tdrop/assets/11522213/2246f4d3-995c-4641-8a2d-fce816e311ff)

**Comment by noctuid** [comment]
Tdrop couldn't do anything you can't already do with `--post-map-hook`.  All tdrop could do is send keypresses to the terminal.  I don't plan to add some option for this because there's no reliable way to run arbitrary commands (e.g. tdrop can't know if you've already typed something or have a TUI application open).  Better to let the users handle everything and simulate keys in situations they know it will work or send commands to the terminal for terminals that support that.

```
# clear when opening
tdrop -am --post-map-hook="xdotool key --clearmodifiers ctrl+l" alacritty
```

**Comment by chris-aeviator** [comment]
@noctuid thanks - this works for me
